# Generated by Django 5.0 on 2026-06-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Body',
            new_name='body',
        ),
    ]
